"""update

Revision ID: 2370b3b596cd
Revises: dcb7168f7ea4
Create Date: 2026-01-21 20:07:46.744744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2370b3b596cd'
down_revision: Union[str, Sequence[str], None] = 'dcb7168f7ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('link', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    # ### end Alembic commands ###
