"""first

Revision ID: 65e3e7e085b9
Revises: 92756bf62d9f
Create Date: 2026-01-14 18:26:12.358525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65e3e7e085b9'
down_revision: Union[str, Sequence[str], None] = '92756bf62d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ublications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('writer', sa.String(length=255), nullable=False),
    sa.Column('journal', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ublications_id'), 'ublications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ublications_id'), table_name='ublications')
    op.drop_table('ublications')
    # ### end Alembic commands ###
