"""first

Revision ID: 92756bf62d9f
Revises: ed528c8c2934
Create Date: 2026-01-14 18:25:26.947326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '92756bf62d9f'
down_revision: Union[str, Sequence[str], None] = 'ed528c8c2934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('researches', 'cover_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researches', sa.Column('cover_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    # ### end Alembic commands ###
