"""update

Revision ID: 92ebbe9f5f2e
Revises: b00f4580dc77
Create Date: 2026-02-01 00:13:39.943094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ebbe9f5f2e'
down_revision: Union[str, Sequence[str], None] = 'b00f4580dc77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_blogs_slug'), 'blogs', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogs_slug'), table_name='blogs')
    op.drop_column('blogs', 'slug')
    # ### end Alembic commands ###
