"""update

Revision ID: b00f4580dc77
Revises: 9575fda86796
Create Date: 2026-01-29 14:16:30.245218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b00f4580dc77'
down_revision: Union[str, Sequence[str], None] = '9575fda86796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.Text(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_id'), 'home', ['id'], unique=False)
    op.create_table('sup_career',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('superiority', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sup_career_id'), 'sup_career', ['id'], unique=False)
    op.create_table('careers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('work_mode', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('apply_link', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_careers_id'), 'careers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_careers_id'), table_name='careers')
    op.drop_table('careers')
    op.drop_index(op.f('ix_sup_career_id'), table_name='sup_career')
    op.drop_table('sup_career')
    op.drop_index(op.f('ix_home_id'), table_name='home')
    op.drop_table('home')
    # ### end Alembic commands ###
