"""update

Revision ID: dcb7168f7ea4
Revises: 887f1f903395
Create Date: 2026-01-17 17:14:48.895913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dcb7168f7ea4'
down_revision: Union[str, Sequence[str], None] = '887f1f903395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_service', sa.Column('service', sa.String(length=45), nullable=False))
    op.drop_column('list_service', 'content')
    op.add_column('services', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('services', sa.Column('icon', sa.String(length=255), nullable=False))
    op.drop_column('services', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.drop_column('services', 'icon')
    op.drop_column('services', 'name')
    op.add_column('list_service', sa.Column('content', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=False))
    op.drop_column('list_service', 'service')
    # ### end Alembic commands ###
